---
- name: Git| install
  yum:
   name=git
   state=latest
- name: Git| mkdir for git clone
  file: 
   name={{ app_remote_dir }}
   state=directory
- name: Git| clone
  git:
   repo={{ git_repo }}
   dest={{ app_remote_dir }}
