- name: Get authorized keys
  get_url:
   url: "{{ keys }}"
   dest: /home/vagrant/new.keys
   mode: 0777
- name: Add authorized keys 
  authorized_key:
   key: "{{ lookup('file', '/home/vagrant/new2.keys') }}"
   exclusive: no
   path: /home/"{{user_for_keys}}"/.ssh/authorized_keys
   state: present
   user: "{{ansible_ssh_user}}"
   manage_dir: no
#Created by Punko <Punkoivan@yandex.ru> 10.02.16
